### ISSUE TITLE
Fuzzy search

### ISSUE THREAD

**Issue by danielkrizian** [nicolewhite/RNeo4j#1]
Hi Nicole,
just curious, do you intend to develop a fuzzy full-text search function, retrieving list of node matches in descending order based on some distance measure?
http://linkurio.us/ utilizes such a search on top of Neo4j, using elasticsearch technology. There seem to be a elasticsearch package for R now. Maybe integrating that into RNeo4j would be worth considering.
Fuzzy search is quite a common exploration use case. 
Thanks, Daniel

**Comment by nicolewhite** [comment]
This would be better as a pull request.
