### ISSUE TITLE
Documentation Method

### ISSUE THREAD

**Issue by darrkj** [nicolewhite/RNeo4j#15]
I was wondering if you had any interest in starting to document this package using Roxygen. Here is a link which introduces some concepts related to roxygen, http://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html.

You can also modify the project in RStudio to run the documentation function when building so updating the help files is automatic. Another perk is  since the roxy style comments are near the actual source code it is easier to keep the two in sync. It also manages the NAMESPACE and DESCRIPTION files by adding functions that use the export tag.

A more detailed discussion can be found here, http://r-pkgs.had.co.nz/man.html

**Comment by nicolewhite** [comment]
I tried using roxygen, but found that it mostly just made my life harder. I couldn't format the spacing / alignment how I wanted, and the way the NAMESPACE is generated isn't ideal.

**Comment by nicolewhite** [comment]
Reopening this; I need to get RNeo4j on CRAN and roxygen will help get my docs in order to pass the CRAN check.
