### ISSUE TITLE
Error in cypher() - invalid JSON

### ISSUE THREAD

**Issue by retrography** [nicolewhite/RNeo4j#18]
Running the following query:
    
    match (g1:Gem)-[r:COAUTHOR]->(g2:Gem) 
    return id(g1) as source, id(g2) as target, r.multiplicity as multiplicity,
    r.source_since as `source.since`, r.source_until as `source.until`, r.source_ceased as `source.ceased`,
    r.target_since as `target.since`, r.target_until as `target.until`, r.target_ceased as `target.ceased`;

results in the following error:

    Error in fromJSON(content, handler, default.size, depth, allowComments,  : 
      invalid JSON input

While the following query:

    match (g1:Gem)-[r:COAUTHOR]->(g2:Gem) 
    return id(g1) as source, id(g2) as target, r.multiplicity as multiplicity,
    r.source_since as `source.since`, r.source_until as `source.until`, r.source_ceased as `source.ceased`,
    r.target_since as `target.since`, r.target_until as `target.until`, r.target_ceased as `target.ceased`
    limit 1000000;

completes successfully.

Given that the query results in only 448005 records (the limit does not actually limit the results), I can't understand why the two queries behave differently. I tried changing names and labels, etc., but that did not improve the behaviour. By the way, both queries run fine on Neo4j.

**Comment by nicolewhite** [comment]
I know this is old, but can you check if 1.3.3 fixes your issue? While I was never able to reproduce your problem, I suspect it was related to another issue https://github.com/nicolewhite/RNeo4j/issues/26 and that switching from RCurl to httr may possibly resolve this.

**Comment by nicolewhite** [comment]
Closing this for now. Reopen if 1.3.3 doesn't fix your issue.

**Comment by retrography** [comment]
@nicolewhite I will test it soon.
