### ISSUE TITLE
Plot method

### ISSUE THREAD

**Issue by darrkj** [nicolewhite/RNeo4j#19]
I have a package where I have been playing with analytic type functionality on top of Neo4j. I added a method to generate a sankey plot from all of the edges and nodes in the database. I think it would be a better fit in RNeo4j though, maybe as plot.graph. Here is an example: https://github.com/darrkj/labyrinth/blob/master/sankey.md

It shows how all of the nodes are connected to all of the other nodes, via the type of edge. Would you be interested in moving this into RNeo4j?

**Comment by nicolewhite** [comment]
Hi, this is neat but I don't think it fits as a built-in RNeo4j function. It's an interesting way to visualize the nodes and relationships in your graph by weight, but it seems like a very focused way to do it, and not a broad function that most people would find useful.
