### ISSUE TITLE
authorization tokens in neo4j 2.2

### ISSUE THREAD

**Issue by zachmayer** [nicolewhite/RNeo4j#20]
I'm trying to connect to a neo4j 2.2 server with a user name and password, and am getting the following error:
```
Error: 401 Unauthorized

{
  "errors" : [ {
    "message" : "No authorization token supplied.",
    "code" : "Neo.ClientError.Security.AuthorizationFailed"
  } ],
  "authentication" : "http://some.ip.address:7474/authentication"
}
```

I know my authorization token: how do I pass it to `startGraph`?

**Comment by nicolewhite** [comment]
Hi, I haven't gotten around to adding any 2.2 functionality. Adding it to my to-do list.

**Comment by zachmayer** [comment]
This isn't just limited to 2.2; any neo4j server with `dbms.security.authorization_enabled=true` will have this problem.

2.2 just switched the default to be `dbms.security.authorization_enabled=true`.

**Comment by nicolewhite** [comment]
I added an `auth_token` argument to `startGraph`:

```
> neo4j = startGraph("http://localhost:7474/db/data/", auth_token="3378f3296094b4e1f7c33dc4287ad757")
> neo4j
< Graph Object > 
$version
[1] "2.2.0-M03"
```

You'll have to upgrade to 1.2.0.

**Comment by zachmayer** [comment]
Awesome, thank you!






—
