### ISSUE TITLE
graph connection error via https self signed certificates

### ISSUE THREAD

**Issue by rvaneijk** [nicolewhite/RNeo4j#21]
In R-Studio I get the following error:
> graph
< Graph Object > 
$version
[1] "2.2.0"
> library(RNeo4j)
> graph = startGraph("https://localhost:7473/db/data/")
Error in function (type, msg, asError = TRUE)  : 
  SSL certificate problem: self signed certificate

In case you want to reproduce the Neo4J setup, I configured the SSL certificate as follows:
$ sudo mkdir -p /var/ssl/neo4j
$ sudo openssl genrsa -des3 -out /var/ssl/ca.key 4096
$ sudo openssl req -new -x509 -days 365 -key /var/ssl/ca.key -out /var/ssl/ca.crt
$ sudo openssl genrsa -des3 -out /var/ssl/neo4j/server.key 4096
$ sudo openssl req -new -key /var/ssl/neo4j/server.key -out /var/ssl/neo4j/server.csr
$ sudo openssl x509 -req -days 365 -in /var/ssl/neo4j/server.csr -CA /var/ssl/ca.crt -CAkey /var/ssl/ca.key -set_serial 01 -out /var/ssl/neo4j/server.crt

Regards,
Rob

**Comment by nicolewhite** [comment]
I've only implemented basic auth; I'll have to take a look at the docs this and see what I can do. Thank you for the reproducible setup.

**Comment by rvaneijk** [comment]
Hi Nicole,

I think a way to solve this is moving from http_request to rcurl. RCurl wraps libcurl, which is capable of dealing with self signed certificates.

Not tested, but could work (StartGraph.R):
Line 22:  response <- getURL(url, ssl.verifypeer = FALSE)

**Comment by nicolewhite** [comment]
Hi,

I use RCurl. `http_request` is a function I wrote, but it uses RCurl. I did not realize this was just a matter of setting an option. I haven't had time to reproduce your setup yet, but I've added the ssl.verifypeer = FALSE option. Can you upgrade to RNeo4j 1.3.1 and verify this works?

**Comment by rvaneijk** [comment]
> Can you upgrade to RNeo4j 1.3.1 and verify this works?
New error, but I think that the self signed error is solved. The new error is due to a certificate problem. I have not tested it with a valid Cmmon Name. The certificate that I generated contains 0.0.0.0 instead of the server domain/ip addres.
I will dig into RCurl a bit more to see how to ignore/suppress certificate validation errors and get back to you. Firefox for instance does not complain about the cerificate even if it is not 100% valid.

> library(RNeo4j)
> graph = startGraph("https://ec2-54-87-95-149.compute-1.amazonaws.com:7473/db/data/")
Error in function (type, msg, asError = TRUE)  : 
  SSL: certificate subject name '0.0.0.0' does not match target host name 'ec2-54-87-95-149.compute-1.amazonaws.com'

**Comment by rvaneijk** [comment]
SOLVED. the ssl.verifypeer = FALSE option requires a valid certificate which can be self-signed.

I tested with a proper self signed certificate. The error is now gone.

> library(RNeo4j)
> graph = startGraph("https://50.16.73.247:7473/db/data/")
> graph
< Graph Object > 
$version
[1] "2.2.1"

BTW: The Neo4j documentation seems to be incorrect. Both key and cert need to be in DER format. Here is my setup:

sudo vi /etc/neo4j/neo4j-server.properties 
# uncomment org.neo4j.server.webserver.address=0.0.0.0
# check: org.neo4j.server.webserver.https.enabled=true
# check: org.neo4j.server.webserver.https.port=7473
# change: org.neo4j.server.webserver.https.cert.location=/var/ssl/neo4j/server.crt
# change: org.neo4j.server.webserver.https.key.location=/var/ssl/neo4j/server.key

now set up access to https
note: both the private key and the certificate need to be in DER format
$ openssl genrsa -des3 -out ca.key 4096
$ openssl req -new -x509 -days 365 -key ca.key -out ca.pem
$ openssl genrsa -des3 -out server.key 4096
$ openssl req -new -key server.key -out server.csr
$ openssl x509 -req -days 365 -in server.csr -CA ca.pem -CAkey ca.key -set_serial 01 -out server.pem
$ sudo mkdir -p /var/ssl/neo4j
$ sudo openssl x509 -outform der -in server.pem -out /var/ssl/neo4j/server.crt
$ sudo openssl rsa -in server.key -inform PEM -out /var/ssl/neo4j/server.key -outform DER
