### ISSUE TITLE
RNeo4j not connecting with dbms.security.auth_enabled=true

### ISSUE THREAD

**Issue by rvaneijk** [nicolewhite/RNeo4j#22]
By default Neo4j is now configured with authentication on. 
# cat neo4j/conf/neo4j-server.properties | grep auth
... dbms.security.auth_enabled=true

It would be nice to connect from RNeo4j and be able to authenticate.

In R-Studio I get the following error:
> graph
< Graph Object > 
$version
[1] "2.2.0"
> library(RNeo4j)
> graph = startGraph("http://192.168.178.88:7474/db/data/")
Error: 401 Unauthorized

{
  "errors" : [ {
    "code" : "Neo.ClientError.Security.AuthorizationFailed",
    "message" : "No authorization header supplied."
  } ]
}

**Comment by nicolewhite** [comment]
You need to provide the username and password.

```
graph = startGraph("http://192.168.178.88:7474/db/data/", username="username", password="password")
```
