### ISSUE TITLE
Error Message appendCypher(): "code" : "Neo.ClientError.Security.AuthorizationFailed"...

### ISSUE THREAD

**Issue by jrzaurin** [nicolewhite/RNeo4j#23]
I have just started with Neo4j v2.2.1, 

I followed the link: http://stackoverflow.com/questions/25295590/how-to-create-nodes-in-rneo4j-using-vectors-or-dataframes 
 and also the demo: http://watch.neo4j.org/video/105896138?_ga=1.174865570.1897839624.1431007064

However, when I try the code within the 1st link, in particular:  
 ```appendCypher(t, query, origin_name = origin_name, dest_name = dest_name, flight_num = flight_num)```
 
I get the error message:
```Error: 401 Unauthorized```
````{```
```  "errors" : [ {```
```    "code" : "Neo.ClientError.Security.AuthorizationFailed",```
```    "message" : "No authorization header supplied."```
```  } ]```
```} ```

(this is the same error I got by doing when typing 
```graph = startGraph("http://localhost:7474/db/data/")``` 
which I solved by including username and password, but here this does not seem to apply...)

I am sure I am doing something wrong and surely the solution is fairly trivial, but after some time trying, I could make use of some help.

By the way, I just though that posting this issue in Stackoverflow (http://stackoverflow.com/questions/30221409/rneo4j-appendcypher-error-error-401-unauthorized) would perhaps reach more RNeo4j users, and it seems I cannot remove it from here. Therefore, whoever replies can do it either here or there, whatever he/she things is better (and sorry for the duplicate). 

Thanks in advance for your time.

**Comment by jrzaurin** [comment]
ok, so someone changed the password, i.e. I was using the old/incorrect password!

In other words: 

```graph = startGraph("http://localhost:7474/db/data/", username = "username", password = "password")```

works fine...sorry for raising the issue.

**Comment by nicolewhite** [comment]
This is a bug. Fixed with https://github.com/nicolewhite/RNeo4j/commit/54139edae66b30f049072106e3d3f18233de5b79

**Comment by jrzaurin** [comment]
thanks!! Nicole
