### ISSUE TITLE
updateProps doesn't seem to work with arrays/vectors

### ISSUE THREAD

**Issue by jpmarindiaz** [nicolewhite/RNeo4j#27]
Hi again Nicole ;)

`updateProps` is not working when one tries to update properties that are vectors(R)/arrays(Neo4j)

I guess the problem lies here:
https://github.com/nicolewhite/RNeo4j/blob/master/R/updateProp.R#L18-19
Maybe using `toJSON` instead of the hardcoded `"` `"` surrounding the properties will fix it.

Here is a reproducible example:
```
library(RNeo4j)
graph = startGraph("http://localhost:7474/db/data/")
graph$version
clear(graph)
mugshots = createNode(graph, "Bar", name = "Mugshots", locations = c("México","USA"))
mugshots$locations

query = "MATCH (p:Bar {name:{name}})
         RETURN p"
m = getSingleNode(graph, query, name = "Mugshots")

updateProp(m, name = "Mugs") 
#OK
updateProp(m,locations = c("México","USA","Canada")) 
#ERROR
```

**Comment by nicolewhite** [comment]
Oops. :) Thanks. Should be an easy fix.

**Comment by nicolewhite** [comment]
This is fixed in 1.3.3.

```
> library(RNeo4j)
> graph = startGraph("http://localhost:7474/db/data/")
> graph$version
[1] "2.2.0"
> clear(graph, input=F)
> mugshots = createNode(graph, "Bar", name = "Mugshots", locations = c("México","USA"))
> mugshots$locations
[1] "México" "USA"   
> 
> query = "MATCH (p:Bar {name:{name}})
+          RETURN p"
> 
> m = getSingleNode(graph, query, name = "Mugshots")
> 
> m = updateProp(m, name = "Mugs") 
> m = updateProp(m,locations = c("México","USA","Canada")) 
> m
< Node Object > 
$locations
[1] "México" "USA"    "Canada"

$name
[1] "Mugs"
```

Another thing to note is that you should reassign the result of `updateProp` back to the same variable. Otherwise your local object won't be updated with the properties. It's still written to the database, but then your local copy is out of date. So instead of this:

```
updateProp(m, name = "Mugs")
```

You should do this:

```
m = updateProp(m, name = "Mugs") 
```

**Comment by jpmarindiaz** [comment]
Hi @nicolewhite 

Me again, I just noticed that now there is a problem when one updates properties that are not arrays.
If I update a node property even though it is not originally an array it forces the property to become an array.

See example:

```
library(RNeo4j)
graph = startGraph("http://localhost:7474/db/data/")
graph$version
clear(graph)
mugshots = createNode(graph, "Bar", name = "Mugshots", locations = c("México","USA"))
mugshots$locations

query = "MATCH (p:Bar {name:{name}})
         RETURN p"
m = getSingleNode(graph, query, name = "Mugshots")

updateProp(m, name = "Mugs") 

m1 <- getSingleNode(graph, query, name = "Mugs")
#NULL
m2 <- getSingleNode(graph, query, name = list("Mugs"))
#OK

```
I first noticed this behavior in the neo4j web interface. After I updated a node's name, it became an array.
before: `name	Mugshots`
after `name [Mugs]`

**Comment by nicolewhite** [comment]
What version of RNeo4j are you on? This was fixed recently.

**Comment by jpmarindiaz** [comment]
1.3.3
I think this is actually a consequence of the fix.
Before the fix, arrays wouldn't get updated.
After the fix, every property seems to be turned into an array when using `updateProp`

**Comment by nicolewhite** [comment]
Yeah, it was. It slipped past my tests because I was only checking that the property was updated correctly on the R object. And in R, I didn't realize that

```
> 3 == c(3)
[1] TRUE
```

So my tests where I had things like

```
n = updateProp(n, age=3)
assert_equal(n$age, 3)
```

passed.

Now I'm using Cypher in my tests to check that it actually got updated correctly. This was fixed as of v.1.3.4 so you just need to update.

**Comment by jpmarindiaz** [comment]
@nicolewhite you rock!
