### ISSUE TITLE
Get full graph into json format gives error?

### ISSUE THREAD

**Issue by smartinsightsfromdata** [nicolewhite/RNeo4j#28]
I think sometimes it is useful to get the full graph (or in alternative a chunk of it) into a json format for later manipulation in R.
From the cypher console I can do the following:
```
:POST /db/data/transaction/commit
  {"statements":[{"statement":"MATCH path = (n)-[r]->(m) RETURN path", "resultDataContents":["graph"]}]}
```
And I can download a json source will all nodes / labels etc.: it sounds exactly what I need: I then can use different types of graph visualisations in R htmlwidgets-based.

I cannot do the same with rneo4j as the query crashes:
```R
> jsonGraph <- '
+ :POST /db/data/transaction/commit
+   {"statements":[{"statement":"MATCH path = (n)-[r]->(m) RETURN path", "resultDataContents":["graph"]}]}
+ '
> jsonStr <- cypher(graph, jsonGraph)
Error: 400 Bad Request

{"message":"Invalid input ':': expected <init> (line 1, column 1 (offset: 0))\n\":POST /db/data/transaction/commit\"\n ^","exception":"SyntaxException","fullname":"org.neo4j.cypher.SyntaxException","stacktrace":["org.neo4j.cypher.internal.compatibility.exceptionHandlerFor2_2$.syntaxException(CompatibilityFor2_2.scala:53)","org.neo4j.cypher.internal.compatibility.exceptionHandlerFor2_2$.syntaxException(CompatibilityFor2_2.scala:52)","org.neo4j.cypher.internal.compiler.v2_2.SyntaxException.mapToPublic(CypherException.scala:128)","org.neo4j.cypher.internal.compatibility.exceptionHandlerFor2_2$.runSafely(CompatibilityFor2_2.scala:109)","org.neo4j.cypher.internal.compatibility.CompatibilityFor2_2$$anon$2.plan(CompatibilityFor2_2.scala:149)","org.neo4j.cypher.ExecutionEngine$$anonfun$liftedTree1$1$1$$anonfun$apply$1.apply(ExecutionEngine.scala:149)","org.neo4j.cypher.ExecutionEngine$$anonfun$liftedTree1$1$1$$anonfun$apply$1.apply(ExecutionEngine.scala:146)","org.neo4
```

What do I do wrong?

**Comment by nicolewhite** [comment]
`cypher` expects a valid Cypher query, which you did not provide.

Perhaps `getPaths` will be useful.

```r
query = "MATCH path = (n)-[r]->(m) RETURN path"
paths = getPaths(graph, query)
```

[This](http://nicolewhite.github.io/2014/12/17/whats-new-rneo4j.html) blog post has a good example of using paths in RNeo4j. I have not used the graph option for resultDataContents before as I never seemed to have a use case for it. Let me know if `getPaths` is a solution; otherwise I'll explore the graph option.

I would also explore returning an edgelist in Cypher, which you can then pass to visualizations quite easily. See examples [here](https://github.com/nicolewhite/neo4j-python-r/tree/master/r).

**Comment by smartinsightsfromdata** [comment]
I think I need to explain a bit better what I would like to achieve.

My plan is to be able to a) store a graph in neo4j (easy thanks to rneo4j); b) send an appropriate query to neo4j;  c) based on the query output, if the graph is small (i.e. less than 1,000 nodes) I plan to just display it in a shiny application using visnetwork.

I have already a simple demo working.  The problem I face is that at the start I would like to show in my visualisation not just one type of edges, but all type of edges in the graph (i.e., for a small graph, the graph in its entirety).
In order to use visnetwork properly, I need to have two data.frames:
- nodes data.frame, with id; label and any value associated
- edges data.frame, with from, to, label of the edges etc.

Through your examples I can do this for one type of edges, for example with the movie graph and your queries:
```
nodes_query <-  "
MATCH (a:Person)-[:ACTED_IN]->(:Movie) RETURN DISTINCT ID(a) AS id, a.name AS name
"

edges_query <-  "
MATCH (a1:Person)-[:ACTED_IN]->(:Movie)<-[:ACTED_IN]-(a2:Person)
RETURN ID(a1) AS source, ID(a2) AS target
"
```
My current challenge is to be able to get:
- in nodes all the nodes of the graph
- in edges all the edges of the graph

Unfortunately getPath gives me a list (of lists) that seems quite complex to unlist.

Is there a simpler resolution to this problem able to generate df's with all nodes and all edges?

(my previous question was based on the assumption that a) it is easier to strip a json file with current packages than do the same on a list of lists; b) I thought that it was possible to get from rneo4j also a json format directly - like you can do from the neo4j console).

**Comment by nicolewhite** [comment]
I don't think returning the entire graph as json is the way to go here. I'm confident I can help you write the Cypher queries to get your graph into visnetwork. Is this the visnetwork package you're referring to?

http://bthieurmel.github.io/visNetwork/

**Comment by smartinsightsfromdata** [comment]
Yes. A very good package. Rocks.

**Comment by smartinsightsfromdata** [comment]
A follow-on question, once we have the query that displays a graph of say 100 nodes as above, is going to be:
- what is the best strategy to select / partition a 10,000 nodes graph to get only a chunk of less than 100 nodes?
- what would be the query associated?

As an example, I understand that I can use in ```cypher``` the clause ```limit 100```, but how would I make sure to get different chunks of 100 nodes every time?

**Comment by nicolewhite** [comment]
I was able to get the entire graph with this code:

**CAUTION: This will delete everything in your Neo4j database and import the sample movie dataset.**
```r
library(visNetwork)
library(RNeo4j)

graph = startGraph("http://localhost:7474/db/data/")
importSample(graph, "movies", input=F)

node_query = "
MATCH n 
RETURN ID(n) AS id, 
       COALESCE(n.name, n.title) AS label,
       LABELS(n)[0] AS group
"

edge_query = "
MATCH (n)-[r]->(m)
RETURN ID(n) AS from,
       ID(m) AS to,
       TYPE(r) AS label
"

nodes = cypher(graph, node_query)
edges = cypher(graph, edge_query)

visNetwork(nodes, edges, width="100%") %>% visEdges(style = "arrow")
```

Note that you'll need to be aware of which properties you want to use as labels; here, I had to use COALESCE to either return the name property or the title property because the Person nodes need to be labeled by name and the Movie nodes need to be labeled by title. So there will be some domain knowledge required here.

As far as getting a random graph, I'd do this:

```r
LIMIT = 100

node_query = "
MATCH n
WITH n, RAND() AS random
ORDER BY random
LIMIT {limit}
RETURN ID(n) AS id, 
       COALESCE(n.name, n.title) AS label,
       LABELS(n)[0] AS group
"

edge_query = "
MATCH (n)-[r]->(m)
WHERE ID(n) IN {ids} AND ID(m) IN {ids}
RETURN ID(n) AS from,
       ID(m) AS to,
       TYPE(r) AS label
"

nodes = cypher(graph, node_query, limit=LIMIT)
edges = cypher(graph, edge_query, ids=nodes$id)

# If you don't want disconnected nodes:
nodes$connected = nodes$id %in% c(edges$from, edges$to)
nodes = nodes[nodes$connected, ]

visNetwork(nodes, edges, width="100%") %>% visEdges(style = "arrow")
```

You can view these examples [here](http://nicolewhite.github.io/examples/visNetwork/rneo4j-visnetwork.html).

**Comment by smartinsightsfromdata** [comment]
Great queries. Thanks!

**Comment by UrbanMap** [comment]
Dear Nicole, thank you for the nice explanations. 
Unfortunately, in RStudio I have a problem with repeated calls to visNetwork. 
As soon as there are nodes with the same id (and label) in the graph, I can display them in the Neo4j browser, but the Viewer-Window of RStudio remains empty. For example, when I run your example script twice, all nodes are doubled, of course. Then the call to visNetwork(nodes, edges) results in an empty view. Is this a problem of how visNetwork handles the input?
Any hint is greatly appreciated.

Best,
Christian

**Comment by nicolewhite** [comment]
Hey, I think that'll happen if your `nodes` data.frame isn't unique by id. Your `edges` data.frame can stay the same, but try this:

```r
nodes = unique(nodes)
visNetwork(nodes, edges)
```

Maybe check this out as well: http://neo4j.com/blog/visualize-graph-with-rneo4j/

The workflow is slightly different than what I did here. First I get an edgelist, and then I grab just the unique values for the `nodes` data.frame.

**Comment by UrbanMap** [comment]
Thank you, Nicole. That was exactly the problem and your solution works.
