### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by kiddjmadd** [nicolewhite/RNeo4j#29]
Hi,
When I try to install per the README.md, I get the following error: 

"Downloading github repo nicolewhite/RNeo4j@master
Error in function (type, msg, asError = TRUE)  : 
certificate problem: self signed certificate in certificate chain"

Could you review?

Thanks!
Jesse Madsen

**Comment by nicolewhite** [comment]
Can you paste the output of `devtools::session_info()` please?

**Comment by nicolewhite** [comment]
This seems to be a devtools / httr bug. Perhaps related to https://github.com/hadley/devtools/issues/579.

Maybe try [this](http://stackoverflow.com/questions/24793863/devtoolsinstall-github-ignore-ssl-cert-verification-failure)? Are you behind a firewall?

**Comment by kiddjmadd** [comment]
The set_config( config( ssl.verifypeer = 0L ) ) worked. Thanks so much!

**Comment by nicolewhite** [comment]
Excellent!
