### ISSUE TITLE
Functionality to leverage the Command Line

### ISSUE THREAD

**Issue by Btibert3** [nicolewhite/RNeo4j#33]
This is an idea for an enhancement, but admittedly I don't know how feasible it is or effecient.  Is it possible to create a function that allows the user to call `neo4j-shell`  through `?system` and import a file of cypher statements? 

Here is my use case.  A nightly job that does:

1.  Data acquisition, cleansing, transforming done with R
2.  Save the data out to csv's for import (same file name/location each run)
3.  Using this library, call a function that would mirror something like `$neo4j-shell -f /path/to/file.cql` where the `.cql` file has the commands with the LOAD CSV statement referencing the CSV files from step 2.

I suppose we could do this all through bash, but given my strengths are mostly within R, I am trying to be lazy and automate my entire workflow totally within R.

**Comment by nicolewhite** [comment]
Sorry if I'm missing something, but what's wrong with

```r
system("neo4j-shell -file /path/to/file.cql")
```

within R?

**Comment by Btibert3** [comment]
When I see it on the screen, absolutely nothing.

**Comment by nicolewhite** [comment]
Haha. :) I don't think it warrants a function in RNeo4j, but it'd be easy to define your own. Assuming you're in the neo4j directory already:

```r
execute_in_shell = function(filepath) {
  system(paste("./neo4j-shell -file", filepath))
}

execute_in_shell("/path/to/file.cql")
```

**Comment by Btibert3** [comment]
Thats where I was going with it in my head earlier, but to your point above, it probably would be more effort to set up the process.  

Thanks for humoring my half-thought-through idea ...
