### ISSUE TITLE
interfacing mazerunner from r with RNeo4j

### ISSUE THREAD

**Issue by smartinsightsfromdata** [nicolewhite/RNeo4j#38]
I've been playing with @kbastani mazerunner: very interesting stuff.  On the other hand I am still very much using R for reporting / graph visualisation and generally to talk to the neo4j instance.

To be able to avoid to interact with neo4j browser entirely I would need to be able to submit to neo4j the `get` to mazerunner via REST.  In Kenny's example below, I need to be able to send:
```
:GET /service/mazerunner/analysis/pagerank/KNOWS
``` 
As the above is not cypher I cannot use RNeo4j `cypher`.  Is there a way in the package to send a REST GET like the above (and to which endpoint should it go?)

If there isn't a way in RNeo4j (and assuming that this usecase is not general enough to develop one), would you be so kind to point me in the right direction - endpoint :) to develop this with say httr?

**Comment by nicolewhite** [comment]
Have you tried 

```r
httr::GET("http://localhost:7474/service/mazerunner/analysis/pagerank/KNOWS")
```

?

**Comment by smartinsightsfromdata** [comment]
Great!

I had to substitute my IP address (the docker's address) but it worked.

Only (minor matter) is that at the browser I get a json answer:
````
{
  "result": "success"
}
````
And now I get:
```
>httr::GET("http://192.168.99.100:7474/service/mazerunner/analysis/pagerank/KNOWS")
Response [http://192.168.99.100:7474/service/mazerunner/analysis/pagerank/KNOWS]
  Date: 2015-09-20 19:32
  Status: 200
  Content-Type: application/json
  Size: 23 B
```
How do I get the `json` success string (so that I can test on it)?

Many thanks for the help by the way!

**Comment by nicolewhite** [comment]
You should be able to do it like this:

```r
> response = httr::GET("http://192.168.99.100:7474/service/mazerunner/analysis/pagerank/KNOWS")
> status = httr::http_status(response)
> status
$category
[1] "success"

$message
[1] "success: (200) OK"

> status$category == "success"
[1] TRUE
```

**Comment by smartinsightsfromdata** [comment]
many thanks :)
