### ISSUE TITLE
shortestPath: Error in file.info(x) : invalid filename argument

### ISSUE THREAD

**Issue by nicolewhite** [nicolewhite/RNeo4j#43]
I believe this is specific to something strange happening in RStudio, as the problem cannot be reproduced in the command line. The shortestPath function completes successfully but this message is inexplicably displayed as an error.

**Comment by kkruups** [comment]
Hi Nicole,

I also see the same behavior for cypher in all three environments commandline, RStudio console/script, R Console.

Here is my commandline output (I labelled the output in my Rscript code output for convenience):

C:\sandbox\r\rcode_commandline>rscript rneoj_getPath_str_test.R
Warning message:
package 'RNeo4j' was built under R version 3.2.5


XXXX Correct str execution List for Comparison XXXXX
List of 2
 $ : num [1:4] 1 2 4 5
 $ :function (x)
 num [1:4] 1 2 4 5
function (x)


XXXXX Error:Unexpected behavior Below  str(p) XXXXX
List of 2
 $ :Error in file.info(x) : invalid filename argument
Calls: str ... str -> str.default -> length -> length.path -> file.info
Execution halted
