### ISSUE TITLE
clear(graph) RNeo4j issues client error: (400) Bad Request

### ISSUE THREAD

**Issue by jagjindersingh** [nicolewhite/RNeo4j#44]
I am using RStudio to create and run the Neo4j graph, and it suddenly started the client error: (400) Bad Request when I try to clear the graph.

> clear(graph)
You are about to delete all nodes, relationships, indexes, and constraints from the graph database. Are you sure? Y/N
1: Y
Error: client error: (400) Bad Request

Graph version is
< Graph > 
$version
[1] "2.3.0"

RStudio is Version 0.99.489

Please help.

**Comment by nicolewhite** [comment]
What version of RNeo4j are you on? You can check with:

```
packageDescription("RNeo4j")["Version"]
```

**Comment by jagjindersingh** [comment]
> packageDescription("RNeo4j")["Version"]
$Version
[1] "1.6.0"

**Comment by nicolewhite** [comment]
There was a breaking change introduced in Neo4j 2.3; it's been fixed in RNeo4j 1.6.1. I don't have 1.6.1 on CRAN yet but you can get it through GitHub. First uninstall RNeo4j, restart R, and then use install_github:

```
devtools::install_github("nicolewhite/RNeo4j")
```

**Comment by jagjindersingh** [comment]
Thanks. I have 1.6.1 RNeo4j now, but when do install_github, it gives me 401 error:
> devtools::install_github("nicolewhite/RNeo4j")
Downloading GitHub repo nicolewhite/RNeo4j@master
Error in download(dest, src, auth) : client error: (401) Unauthorized

What am I doing incorrect?

**Comment by nicolewhite** [comment]
I just got it on CRAN. Can you try with install.packages?

```
install.packages("RNeo4j")
```

**Comment by jagjindersingh** [comment]
Sorry for the late reply. I could not get it working, so I am now working directly with Neo4j-shell writing Cypher queries. Thank you for your help, Nicole.
