### ISSUE TITLE
ig = graph.data.frame gives error

### ISSUE THREAD

**Issue by bastianpeter** [nicolewhite/RNeo4j#53]
Hi,

I am going through your tutorial (https://github.com/nicolewhite/RNeo4j).

When I am in the Graph Algorithms part (https://github.com/nicolewhite/RNeo4j#graph-algorithms) and I execute the following:
query = "MATCH (n)-->(m) RETURN n.name, m.name "

edgelist = cypher(graph, query)

ig = graph.data.frame(edgelist, directed=F)

I get the following error:
Error: could not find function "graph.data.frame"

What could it be?

Many thanks in advance for your help.

By the way, great job on the RNeo4j package - it's a blast.

Greetings from Switzerland,

Bastian

**Comment by nicolewhite** [comment]
Hey, do you have `igraph` installed?

**Comment by bastianpeter** [comment]
Hi,

Thank you so much - that was the mistake. I forgot the double quotes in install.packages(igraph).
Typical Matlab transfuge mistake ;-)

Thanks for your help and I wish you a nice weekend.

**Comment by nicolewhite** [comment]
You too! :)
