### ISSUE TITLE
list returned by cypherToList results in error when list evaluated by str

### ISSUE THREAD

**Issue by kkruups** [nicolewhite/RNeo4j#55]
When executing the following:

```
p =  cypherToList(neo4j, query)
str(p)

```

str indicates the following error:

`file.info(x) File name argument is invalid`

This behavior is not observed when using deprecated getPaths (str evaluates successfully)

```
p = getPaths(neo4j, query)
str(p)

```
Let me know if you need any further details.

**Comment by nicolewhite** [comment]
Hi, so this is definitely related to https://github.com/nicolewhite/RNeo4j/issues/43. I can't reproduce the problem on the command line; it seems to only happen in RStudio. Can you confirm?

**Comment by kkruups** [comment]
Hi Nicole,

I also see the same behavior in all three environments commandline (correction: getPaths also indicates the same error), RStudio console/script, R Console. Here is link to code gist/github:
[ rscript code ](https://gist.github.com/kkruups/17f96fa12d6b81124a0f4f331c2c4e67)

Here is my commandline output (I labelled the output in my Rscript code output for convenience):

C:\sandbox\r\rcode_commandline>rscript rneoj_getPath_str_test.R
Warning message:
package 'RNeo4j' was built under R version 3.2.5


XXXX Correct str execution List for Comparison XXXXX
List of 2
 $ : num [1:4] 1 2 4 5
 $ :function (x)
 num [1:4] 1 2 4 5
function (x)


**XXXXX Error:Unexpected behavior Below  str(p) XXXXX**
List of 2
 **$ :Error in file.info(x) : invalid filename argument**
Calls: str ... str -> str.default -> length -> length.path -> file.info
Execution halted

**Comment by nicolewhite** [comment]
Hmm, for some reason I only see the behavior in RStudio. Regardless I'm not sure how to troubleshoot because none of these functions use a filename argument.

**Comment by ernestoe** [comment]
Not sure if related, but if I try to write.csv a dataframe obtained from a query that uses collect, I get the following error:

  unimplemented type 'list' in 'EncodeElement' 

most probably related to a column being made of R lists (arrays in query result). Is there any way to go around this?

**Comment by happyshows** [comment]
same here

```
> p = shortestPath(greta, "LIKES", shannon, max_depth=4, cost_property="weight")
Error in file.info(x) : invalid filename argument

> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] RNeo4j_1.7.0

loaded via a namespace (and not attached):
[1] httr_1.2.1           R6_2.1.3             tools_3.3.0         
[4] withr_1.0.1          curl_0.9.7           memoise_1.0.0       
[7] git2r_0.15.0         digest_0.6.10        devtools_1.11.1.9000
```

**Comment by nicolewhite** [comment]
Yes, again, there's not much I can do. There's no stacktrace and Google yields nothing relevant. This is obviously not a file location issue; nothing in that function accesses the file system at all.

**Comment by nicolewhite** [comment]
Wow, I didn't find this last time I searched for this issue.

https://support.bioconductor.org/p/79059/

This def seems to be the problem. I imagine I can fix it shortly.

**Comment by nicolewhite** [comment]
http://stackoverflow.com/questions/39185171/how-to-override-exported-function-from-r-package-listed-in-imports
