### ISSUE TITLE
Error on: importSample(graph, "dfw");

### ISSUE THREAD

**Issue by Eulerianial** [nicolewhite/RNeo4j#56]
Hello,

I am seeing following error while running a shiny app (http://nicolewhite.github.io/2014/06/30/create-shiny-app-neo4j-graphene.html) :
importSample(graph, "dfw");
You are about to delete all nodes, relationships, indexes, and constraints from the graph database. Are you sure? Y/N
1: Y
Error: Client error: (400) Bad Request
Neo.ClientError.Statement.SyntaxError
Parentheses are required to identify nodes in patterns, i.e. (_5) (line 288, column 8 (offset: 10571))
"create _5-[:`IN_TERMINAL`]->_0"

Am I missing something?

Best,
Vijay

**Comment by nicolewhite** [comment]
The Cypher script was written for Neo4j < 3.0 and you're on Neo4j 3.0. @jexp fixed it in #57.

**Comment by Eulerianial** [comment]
Yes @nicolewhite we could fix it with the help from @jexp. We could update the script and the app is running at https://ashutosh-sharma.shinyapps.io/demo/ Further, I am building few more things would post on the Slack channel.

**Comment by omennemo** [comment]
This fix for the query isn't available as part of the install from CRAN. It is still in the old ( <3.0 ) query format.
