### ISSUE TITLE
Error in cypher(graph, query) - "You must query for tabular results when using this function."

### ISSUE THREAD

**Issue by kavuri** [nicolewhite/RNeo4j#61]
I have data dumped into neo4j as individual nodes on which I want to run my R model to do stuff. When I try to run the query
`MATCH (node:rs_transaction) WHERE node.mem_id='1000137217882093' RETURN node"`
in `cypher(graph, query)`, I get an error

`Error in cypher.graph(graph, query) : 
  You must query for tabular results when using this function.`

When I run the same query using `cypherToList(graph, query)`, it works fine

And surely, the query runs fine on neo4j itself. What could possibly be going wrong?

**Comment by Btibert3** [comment]
In short, the functions appear to be operating as expected.

Take a look at the behavior of `?cypher` and `cypherToList`.  `cypher` expects tabular data to be returned, and from the sounds of it above, `cypherToList` would be more appropriate for your query.

**Comment by kavuri** [comment]
To make `cypher` work, I had to return the specific fields, like n.name,n.amount etc. to get dataframe. This works for me and I can go with this. Thanks

**Comment by Btibert3** [comment]
@kavuri That makes sense, `cypher` is expecting results in the form of a data.frame.  Glad you were able to keep moving forward!
